# Generated by Django 4.2.18 on 2025-01-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0002_alter_tutor_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='specialization',
            new_name='course_specialization',
        ),
    ]
